package com.silverminer.moreore.util.helpers.silver_dim;

public class ObjHolder {
	public static String SILVER_DIM_JSON = "{\r\n" + "  \"generate_features\": true,\r\n"
			+ "  \"bonus_chest\": false,\r\n" + "  \"seed\": 0,\r\n" + "  \"dimensions\": {\r\n"
			+ "    \"minecraft:overworld\": {\r\n" + "      \"type\": \"minecraft:overworld\",\r\n"
			+ "      \"generator\": {\r\n" + "        \"type\": \"minecraft:noise\",\r\n"
			+ "        \"seed\": 0,\r\n" + "        \"biome_source\": {\r\n"
			+ "          \"type\": \"minecraft:vanilla_layered\",\r\n" + "          \"seed\": 0\r\n"
			+ "        },\r\n" + "        \"settings\": \"minecraft:overworld\"\r\n" + "      }\r\n" + "    },\r\n"
			+ "    \"minecraft:the_nether\": {\r\n" + "      \"type\": \"minecraft:the_nether\",\r\n"
			+ "      \"generator\": {\r\n" + "        \"type\": \"minecraft:noise\",\r\n"
			+ "        \"seed\": 0,\r\n" + "        \"biome_source\": {\r\n"
			+ "          \"type\": \"minecraft:multi_noise\",\r\n" + "          \"seed\": 0,\r\n"
			+ "          \"altitude_noise\": {\r\n" + "            \"firstOctave\": -7,\r\n"
			+ "            \"amplitudes\": [\r\n" + "              1,\r\n" + "              1\r\n" + "            ]\r\n"
			+ "          },\r\n" + "          \"temperature_noise\": {\r\n" + "            \"firstOctave\": -7,\r\n"
			+ "            \"amplitudes\": [\r\n" + "              1,\r\n" + "              1\r\n" + "            ]\r\n"
			+ "          },\r\n" + "          \"humidity_noise\": {\r\n" + "            \"firstOctave\": -7,\r\n"
			+ "            \"amplitudes\": [\r\n" + "              1,\r\n" + "              1\r\n" + "            ]\r\n"
			+ "          },\r\n" + "          \"weirdness_noise\": {\r\n" + "            \"firstOctave\": -7,\r\n"
			+ "            \"amplitudes\": [\r\n" + "              1,\r\n" + "              1\r\n" + "            ]\r\n"
			+ "          },\r\n" + "          \"biomes\": [\r\n" + "            {\r\n"
			+ "              \"biome\": \"minecraft:nether_wastes\",\r\n" + "              \"parameters\": {\r\n"
			+ "                \"altitude\": 0,\r\n" + "                \"temperature\": 0,\r\n"
			+ "                \"humidity\": 0,\r\n" + "                \"weirdness\": 0,\r\n"
			+ "                \"offset\": 0\r\n" + "              }\r\n" + "            },\r\n" + "            {\r\n"
			+ "              \"biome\": \"minecraft:soul_sand_valley\",\r\n" + "              \"parameters\": {\r\n"
			+ "                \"altitude\": 0,\r\n" + "                \"temperature\": 0,\r\n"
			+ "                \"humidity\": -0.5,\r\n" + "                \"weirdness\": 0,\r\n"
			+ "                \"offset\": 0\r\n" + "              }\r\n" + "            },\r\n" + "            {\r\n"
			+ "              \"biome\": \"minecraft:crimson_forest\",\r\n" + "              \"parameters\": {\r\n"
			+ "                \"altitude\": 0,\r\n" + "                \"temperature\": 0.4,\r\n"
			+ "                \"humidity\": 0,\r\n" + "                \"weirdness\": 0,\r\n"
			+ "                \"offset\": 0\r\n" + "              }\r\n" + "            },\r\n" + "            {\r\n"
			+ "              \"biome\": \"minecraft:warped_forest\",\r\n" + "              \"parameters\": {\r\n"
			+ "                \"altitude\": 0,\r\n" + "                \"temperature\": 0,\r\n"
			+ "                \"humidity\": 0.5,\r\n" + "                \"weirdness\": 0,\r\n"
			+ "                \"offset\": 0.375\r\n" + "              }\r\n" + "            },\r\n"
			+ "            {\r\n" + "              \"biome\": \"minecraft:basalt_deltas\",\r\n"
			+ "              \"parameters\": {\r\n" + "                \"altitude\": 0,\r\n"
			+ "                \"temperature\": -0.5,\r\n" + "                \"humidity\": 0,\r\n"
			+ "                \"weirdness\": 0,\r\n" + "                \"offset\": 0.175\r\n" + "              }\r\n"
			+ "            }\r\n" + "          ]\r\n" + "        },\r\n"
			+ "        \"settings\": \"minecraft:nether\"\r\n" + "      }\r\n" + "    },\r\n"
			+ "    \"minecraft:the_end\": {\r\n" + "      \"type\": \"minecraft:the_end\",\r\n"
			+ "      \"generator\": {\r\n" + "        \"type\": \"minecraft:noise\",\r\n"
			+ "        \"seed\": 0,\r\n" + "        \"biome_source\": {\r\n"
			+ "          \"type\": \"minecraft:the_end\",\r\n" + "          \"seed\": 0\r\n"
			+ "        },\r\n" + "        \"settings\": \"minecraft:end\"\r\n" + "      }\r\n" + "    },\r\n"
			+ "    \"dimensions:silver_dimension\": {\r\n" + "      \"type\": {\r\n"
			+ "        \"name\": \"dimensions:silver_dimension\",\r\n" + "        \"ultrawarm\": false,\r\n"
			+ "        \"natural\": true,\r\n" + "        \"piglin_safe\": false,\r\n"
			+ "        \"respawn_anchor_works\": true,\r\n" + "        \"bed_works\": true,\r\n"
			+ "        \"has_raids\": false,\r\n" + "        \"has_skylight\": true,\r\n"
			+ "        \"has_ceiling\": false,\r\n" + "        \"coordinate_scale\": 1,\r\n"
			+ "        \"ambient_light\": 0,\r\n" + "        \"logical_height\": 256,\r\n"
			+ "        \"infiniburn\": \"minecraft:infiniburn_overworld\"\r\n" + "      },\r\n"
			+ "      \"generator\": {\r\n" + "        \"type\": \"minecraft:noise\",\r\n"
			+ "        \"seed\": 0,\r\n" + "        \"biome_source\": {\r\n"
			+ "          \"type\": \"moreore:silver\",\r\n" + "          \"seed\": 0,\r\n"
			+ "          \"biomes\": [\r\n" + "            \"minecraft:river\",\r\n"
			+ "            \"minecraft:frozen_river\",\r\n" + "            \"minecraft:plains\",\r\n"
			+ "            \"minecraft:forest\",\r\n" + "            \"minecraft:taiga\",\r\n"
			+ "            \"minecraft:jungle\",\r\n" + "            \"minecraft:desert\",\r\n"
			+ "            \"minecraft:badlands\",\r\n" + "            \"minecraft:swamp\",\r\n"
			+ "            \"moreore:silver_tale\",\r\n" + "            \"moreore:golden_mountains\",\r\n"
			+ "            \"moreore:death_ice_tale\",\r\n" + "			\"minecraft:dark_forest_hills\",\r\n"
			+ "			\"minecraft:dark_forest\"\r\n" + "          ],\r\n" + "          \"biome_size\": 37\r\n"
			+ "        },\r\n" + "        \"settings\": \"moreore:silver_dimension\"\r\n" + "      }\r\n" + "    }\r\n"
			+ "  }\r\n" + "}\r\n" + "";
}